openapi: 3.0.3
info:
  title: Bookshelve API
  description: |-
    Request informations about books from Google Books and other resources
  contact:
    email: josua@blejeru.com
  license:
    name: MIT
    url: http://github.com/josuablejeru/bookshelves-api
  version: 0.1.0
servers:
  - url: "<API-GATEWAY-URL>"
tags:
  - name: books
    description: everything related to books
paths:
  /bookshelve/books:
    get:
      tags:
        - books
      summary: get my public bookshelve
      description: Returns a collection of books I found valuable
      operationId: getBookshelveBooks
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BookResponse"

  /openapi:
    get:
      summery: the openapi definition of this api
      description: Returns this openapi definition to be used by external services
      operationId: getOpenapiDefinition
      responses:
        "200":
          description: return openapi definition as JSON
          content:
            application/json:
              schema: {}

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: XrQcrgEACAAJ
        title:
          type: string
          example: The DevOps Handbook
        subtitle:
          type: string
          example: How to Create World-Class Speed, Reliability, and Security in Technology Organizations"
        authors:
          type: array
          items:
            type: string
          example:
            - "Gene Kim"
            - "Patrick Debois"
            - "John Willis"
            - "Jez Humble"
        publishedDate:
          type: string
          format: time
          example: "2015-10-07"
        description:
          type: string
          example: |
            For decades, technology leaders have struggled to balance agility,
            reliability, and security, and the consequences of failure have never been greater.
            The effective management of technology is critical for business competitiveness. High ...
        identifiers:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                example: ISBN_10
              identifier:
                type: string
                example: "1942788002"
        imageLinks:
          type: object
          properties:
            smallThumbnail:
              type: string
              format: uri
              example: "http://books.google.com/books/content?id=XrQcrgEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api"
            thumbnail:
              type: string
              format: uri
              example: http://books.google.com/books/content?id=XrQcrgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api

    BookResponse:
      type: object
      properties:
        response:
          type: array
          items:
            allOf:
              - $ref: "#/components/schemas/Book"
